/home/suzhifeng/work/github/ea/./sim/tb/uart_tb.v
/home/suzhifeng/work/github/ea/./sim/tb/decouple/decouple_tb.v
/home/suzhifeng/work/github/ea/./sim/tb/dpa/dpa_tb.v
/home/suzhifeng/work/github/ea/./sim/tb/test_gen_pattern_tb.v
/home/suzhifeng/work/github/ea/./sim/tb/mac/mdio/phy_mdio_port.v
/home/suzhifeng/work/github/ea/./sim/tb/mac/mdio/mdio_tb.v
/home/suzhifeng/work/github/ea/./sim/tb/reset_gen.v
/home/suzhifeng/work/github/ea/./sim/tb/reg/uart2apb_tb.v
/home/suzhifeng/work/github/ea/./sim/tb/reg/uart2reg_tb.v
/home/suzhifeng/work/github/ea/./sim/clock_gen.v
