/home/suzhifeng/work/github/ea/src/./rgmii_phy_if.v
/home/suzhifeng/work/github/ea/src/./eth_axis_tx.v
/home/suzhifeng/work/github/ea/src/./axis_adapter.v
/home/suzhifeng/work/github/ea/src/./arbiter.v
/home/suzhifeng/work/github/ea/src/./test_receiver.v
/home/suzhifeng/work/github/ea/src/./debounce_switch.v
/home/suzhifeng/work/github/ea/src/./axis_async_fifo_adapter.v
/home/suzhifeng/work/github/ea/src/./eth_mac_1g_rgmii_fifo.v
/home/suzhifeng/work/github/ea/src/./axis_gmii_rx.v
/home/suzhifeng/work/github/ea/src/./eth_axis_rx.v
/home/suzhifeng/work/github/ea/src/./uart_rx.v
/home/suzhifeng/work/github/ea/src/./eth_arb_mux.v
/home/suzhifeng/work/github/ea/src/./lfsr.v
/home/suzhifeng/work/github/ea/src/./mac_ctrl_rx.v
/home/suzhifeng/work/github/ea/src/./sync_reset.v
/home/suzhifeng/work/github/ea/src/./ssio_ddr_in.v
/home/suzhifeng/work/github/ea/src/./mac_ctrl_tx.v
/home/suzhifeng/work/github/ea/src/./iddr.v
/home/suzhifeng/work/github/ea/src/./decouple.v
/home/suzhifeng/work/github/ea/src/./test_gen_pattern.v
/home/suzhifeng/work/github/ea/src/./uart_tx.v
/home/suzhifeng/work/github/ea/src/./test_sender.v
/home/suzhifeng/work/github/ea/src/./axis_gmii_tx.v
/home/suzhifeng/work/github/ea/src/./fpga.v
/home/suzhifeng/work/github/ea/src/./mac_pause_ctrl_rx.v
/home/suzhifeng/work/github/ea/src/./axis_async_fifo.v
/home/suzhifeng/work/github/ea/src/./eth_mac_1g.v
/home/suzhifeng/work/github/ea/src/./oddr.v
/home/suzhifeng/work/github/ea/src/./eth_mac_1g_rgmii.v
/home/suzhifeng/work/github/ea/src/./fpga_core.v
/home/suzhifeng/work/github/ea/src/./mac_pause_ctrl_tx.v
